cas.authn.accept.users: jleleu::jleleu,leleuj::leleuj

cas.tgc.secure: false
cas.tgc.same-site-policy: Lax

cas.tgc.crypto.enabled: false
cas.webflow.crypto.enabled: false

cas.server.name: http://localhost:8080
cas.server.prefix: http://localhost:8080/cas
cas.host.name: castest

cas.authn.oauth.code.timeToKillInSeconds: 30000
cas.authn.oauth.code.numberOfUses: 10000

cas.ticket.st.numberOfUses: 1000
cas.ticket.st.timeToKillInSeconds: 10000

cas.serviceRegistry.json.location: classpath:/services
cas:

